eval(File.read(File.dirname(__FILE__) + '/../core_dependencies.rb'))
eval(File.read(File.dirname(__FILE__) + '/../all_dependencies.rb'))

group :test do
  gem 'capybara',                 '~> 2.1'
  gem 'selenium-webdriver'
  gem 'poltergeist'
  gem 'launchy'
  gem 'handy_controller_helpers', '0.0.3'
end

gem 'gaku_core', path: '../core'
gemspec

