AsciiIdentifiers:
  Enabled: false

AsciiComments:
  Enabled: false

AccessorMethodName:
  Enabled: false

LineLength:
  Max: 119

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

AllCops:
  Exclude:
    - '**/spec/dummy/**'
<<<<<<< HEAD
    - 'bin/**'
    - '**/bin/**'
    - '**/db/schema.rb'
    - '**/pkg/**'
    - 'pkg/**'
=======
>>>>>>> staging
  RunRailsCops: false