AsciiIdentifiers:
  Enabled: false

AsciiComments:
  Enabled: false

AccessorMethodName:
  Enabled: false

LineLength:
  Max: 119

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

SingleLineBlockParams:
  Enabled: false

AllCops:
  Exclude:
    - '**/spec/dummy/**/*'
    - 'bin/**/*'
    - '**/bin/**/*'
    - '**/db/schema.rb'
    - '**/pkg/**/*'
    - 'pkg/**/*'
    - '**/config/initializers/**/*'
    - '**/db/migrate/**/*'
    - '**/lib/generators/**/*'

Rails:
  Enabled: true
