language: ruby

sudo: false

rvm:
  - 2.2

addons:
  postgresql: 9.4

services:
  - redis-server
  - postgresql

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - psql --version
  - phantomjs --version
  - psql -c 'create database gaku_test;' -U postgres
  - psql gaku_test -c 'CREATE EXTENSION IF NOT EXISTS hstore' -U postgres

bundler_args: -j4 --without development production

before_install:
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"

script:
  - bundle exec rake test_app
  - I18N=1 bundle exec rspec $SUITE

env:
  - GEM=core SUITE="spec/models spec/lib spec/services"
  - GEM=frontend SUITE="spec/controllers spec/routing spec/requests"
  - GEM=admin SUITE="spec/controllers spec/routing"
  - GEM=frontend SUITE=spec/features/students SELENIUM=1
  - GEM=frontend SUITE=spec/features/other SELENIUM=1
  - GEM=admin SUITE=spec/features SELENIUM=1

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#gaku"
