before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sudo psql --version
  - phantomjs --version
  - sudo apt-get install postgresql-contrib-9.3 -qq
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database gaku_test;' -U postgres

bundler_args: --without production

env:
  - TEST_SUITE=models GEM=core DB=postgres
  - TEST_SUITE=controllers GEM=frontend DB=postgres
  - TEST_SUITE=integration GEM=frontend DB=postgres
  - TEST_SUITE=routing GEM=frontend DB=postgres
  - TEST_SUITE=controllers GEM=admin DB=postgres
  - TEST_SUITE=routing GEM=admin DB=postgres
  - SELENIUM=1 TEST_SUITE=features GEM=frontend DB=postgres
  - SELENIUM=1 TEST_SUITE=features GEM=admin DB=postgres

before_install:
  #- gem install bundler --pre
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"

script:
  - bundle exec rake test_app
  - I18N=1 bundle exec rspec spec/$TEST_SUITE

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#gaku"

rvm:
  - 2.0.0