before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
env:
  - DB=mysql
  - DB=postgres
script:
  - "export DISPLAY=:99.0"
  - "alias set_gemfile='export BUNDLE_GEMFILE=\"`pwd`/Gemfile\"'"
  - "cd core; set_gemfile; bundle install --quiet; SELENIUM=1 I18N=1 bundle exec rspec spec"
  - "cd ../admissions; set_gemfile; bundle install --quiet; SELENIUM=1 I18N=1 bundle exec rspec spec"

notifications:
  email:
    - false
  irc:
    use_notice: true
    skip_join: true
    channels:
      - "irc.freenode.org#gaku"
rvm:
  - 1.9.2
  - 1.9.3
