language: ruby

rvm:
  - 2.2

services:
  - redis-server

addons:
  postgresql: 9.3

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sudo psql --version
  - phantomjs --version
  - sudo apt-get install postgresql-contrib-9.3 -qq
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database gaku_test;' -U postgres

bundler_args: -j4 --without development production

before_install:
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"

script:
  - bundle exec rake test_app
  - rake db:migrate RAILS_ENV=test
  - I18N=1 bundle exec rspec $SUITE

env:
  - GEM=core SUITE="spec/models spec/lib spec/services"
  - GEM=frontend SUITE="spec/controllers spec/routing spec/requests"
  - GEM=admin SUITE="spec/controllers spec/routing"
  - GEM=frontend SUITE=spec/features/students SELENIUM=1
  - GEM=frontend SUITE=spec/features/other SELENIUM=1
  - GEM=admin SUITE=spec/features SELENIUM=1

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#gaku"
