before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - psql -c 'create database gaku_test;' -U postgres
bundler_args: --without development production --quiet
env:
  - GEM=admissions DB=postgres
  - GEM=core DB=postgres
before_install:
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"
script:
  - bundle exec rake test_app
  - SELENIUM=1 I18N=1 bundle exec rspec

notifications:
  email:
    - false
  irc:
    use_notice: true
    skip_join: true
    channels:
      - "irc.freenode.org#gaku"
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
