services:
  - redis-server

before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sudo psql --version
  - phantomjs --version
  - sudo apt-get install postgresql-contrib-9.3 -qq
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database gaku_test;' -U postgres

bundler_args: -j4 --without development production

env:
  - GEM=core SUITE=spec/models
  - GEM=frontend SUITE="spec/controllers spec/routing"
  - GEM=admin SUITE="spec/controllers spec/routing"
  - GEM=frontend SUITE=spec/features SELENIUM=1
  - GEM=admin SUITE=spec/features SELENIUM=1
  - GEM=archive SELENIUM=1

before_install:
  #- gem install bundler --pre
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"

script:
  - bundle exec rake test_app
  - I18N=1 bundle exec rspec $SUITE

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#gaku"

rvm:
  - 2.1.0
