version: '2'
services:
  web:
    environment:
      - RAILS_ENV=development
    build: .
    command: "bin/check_postgres.sh bundle exec rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/gaku
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:9.6.5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:4.0.1
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local
