version: '2'
services:
  web:
    environment:
      - RAILS_ENV=development
      - REDIS_HOST=redis
    build: .
    command: "bin/check_postgres.sh bundle exec rails server -b 0.0.0.0 -p 9000"
    ports:
      - "9000:9000"
    volumes:
      - .:/gaku
      - uploads:/app/uploads
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:9.6.5
    ports:
      - "9001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:4.0.1
    ports:
      - "9002:6379"

volumes:
  postgres-data:
    driver: local
  uploads:
    driver: local
