version: 2
jobs:
  build:
    docker:
       - image: Dockerfile.testing
    working_directory: ~/tmp

    steps:
      - checkout

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
