require 'rake'
require 'rake/testtask'
require 'rake/packagetask'
require 'rubygems/package_task'

desc 'Release to gemcutter'
task :release do
  version = File.read(File.expand_path('../../VERSION', __FILE__)).strip
  cmd = "cd pkg && gem push gaku_testing-#{version}.gem"
  puts cmd
  system cmd
end
