require 'rake'
require 'rake/testtask'
require 'rake/packagetask'
require 'rubygems/package_task'

spec = eval(File.read('gaku_testing.gemspec'))

Gem::PackageTask.new(spec) do |p|
  p.gem_spec = spec
end

desc 'Release to gemcutter'
task :release do
  version = File.read(File.expand_path('../../VERSION', __FILE__)).strip
  cmd = "cd pkg && gem push gaku_testing-#{version}.gem"
  puts cmd
  system cmd
end
