eval(File.read(File.dirname(__FILE__) + '/../gaku_engine_dependencies.rb'))

group :development, :test do
  gem 'rspec'
  gem 'sidekiq'
  gem 'rspec-sidekiq'
  gem 'guard'
  gem 'rubocop'
  gem 'guard-rubocop'
end

gemspec
