eval(File.read(File.dirname(__FILE__) + '/../gaku_dependencies.rb'))
eval(File.read(File.dirname(__FILE__) + '/../web/Gemfile'))
gem 'gaku_core', path: '../core'
gem 'gaku_web', path: '../web'
gemspec
