#ActiveRecord::Fixtures.create_fixtures("#{Rails.root}/db/default/", 'contact_types')
ContactType.create(:id => 1, :name => "Home Phone")
ContactType.create(:id => 2, :name => "Work Phone")
ContactType.create(:id => 3, :name => "Mobile Phone")
ContactType.create(:id => 4, :name => "Phone")
ContactType.create(:id => 5, :name => "E-Mail")
ContactType.create(:id => 6, :name => "Mobile Mail")
ContactType.create(:id => 7, :name => "Skype")
ContactType.create(:id => 8, :name => "Google Plus")
ContactType.create(:id => 9, :name => "Facebook")
ContactType.create(:id => 10, :name => "twitter")
