#ActiveRecord::Fixtures.create_fixtures("#{Rails.root}/db/default/", 'contact_types')
Gaku::ContactType.create(:id => 1, :name => "Home Phone")
Gaku::ContactType.create(:id => 2, :name => "Work Phone")
Gaku::ContactType.create(:id => 3, :name => "Mobile Phone")
Gaku::ContactType.create(:id => 4, :name => "Phone")
Gaku::ContactType.create(:id => 5, :name => "E-Mail")
Gaku::ContactType.create(:id => 6, :name => "Mobile Mail")
Gaku::ContactType.create(:id => 7, :name => "Skype")
Gaku::ContactType.create(:id => 8, :name => "Google Plus")
Gaku::ContactType.create(:id => 9, :name => "Facebook")
Gaku::ContactType.create(:id => 10, :name => "twitter")
