#ActiveRecord::Fixtures.create_fixtures("#{Rails.root}/db/default/", 'class_groups')
Gaku::ClassGroup.create(:name => 'Biology')
Gaku::ClassGroup.create(:name => 'Math')
Gaku::ClassGroup.create(:name => 'Literature')
Gaku::ClassGroup.create(:name => 'A組', :grade => 1)
Gaku::ClassGroup.create(:name => 'A組', :grade => 2)
Gaku::ClassGroup.create(:name => 'さくら組', :grade => 0)
Gaku::ClassGroup.create(:name => 'マルチメディア専攻', :grade => 1)
