require 'rubygems'
require 'bundler'
require 'rake'
require 'rake/testtask'
require 'rake/packagetask'
require 'rubygems/package_task'
require 'gaku/testing/common_rake'

Bundler::GemHelper.install_tasks

task default: :spec

desc 'Generates a dummy app for testing'
task :test_app do
  ENV['LIB_NAME'] = 'gaku/api'
  Rake::Task['common:test_app'].invoke
end

desc 'start testing'
task :start_testing do
  ENV['LIB_NAME'] = 'gaku/core'
  Rake::Task['common:start_testing'].invoke
end

desc 'stop testing'
task :stop_testing do
  ENV['LIB_NAME'] = 'gaku/core'
  Rake::Task['common:stop_testing'].invoke
end
